### ISSUE TITLE
Simple tool to upload data on openahmedabad.org

### ISSUE THREAD

**Issue by shravan91** [DatameetAMD/open-ahmedabad-web#1]
It would be great to have a simple tool to **upload** data. Although the tool should be designed in a way that it is easier for administrators to see the data before it is published on the website.

**Comment by gnatih** [comment]
How does one access the openahmedabad.org website source and make changes?

**Comment by jimishio** [comment]
Hello people,

For anyone who wants to contribute to openahmedabad.org website it self, please clone/fork this [repository](https://github.com/DatameetAMD/DatameetAMD.github.io) and start working on your UI/Feature implementation.

If you guys want to add more projects under this organizatoin, please open a new issue in [bucket-list repository](https://github.com/DatameetAMD/bucket-list) and we will see create new project repo for you guys.

For uploading data we are following same process as per projects. 

Thank you!

**Comment by gnatih** [comment]
[DatameetAMD.github.io](https://github.com/DatameetAMD/DatameetAMD.github.io) is clearly not the repo for [openahmedabad.org](http://openahmedabad.org) website. Or am I confusing the two?
