### ISSUE TITLE
Shuttle rickshaw (Shared auto) data for Ahmedabad

### ISSUE THREAD

**Issue by dhaval-shukla** [DatameetAMD/open-ahmedabad-web#2]
I will be starting to map the shuttle rickshaw routes of Ahmedabad from next week. Will be nice to have some people to help me :-)

**Comment by ndkcha** [comment]
what tool are you using to map the shuttle rickshaw right now ?

**Comment by dhaval-shukla** [comment]
hey

My tracks and open gps. i turn on 2 apps at once incase once of them faults

I have only sat in certain shuttle rickshaws and tracked them using these
apps. and then mapped some of them on QGIS.

**Comment by ndkcha** [comment]
Are you uploading the data on your personal cloud ? or their public cloud storage ?

**Comment by ndkcha** [comment]
@shukla777 Can you share the sample data that you are upload ?

**Comment by hypothal** [comment]
Hi Dhaval,

It will be of great interest if we can publish the shared auto data on
openahmedabad.

Best regards
Mahroof

**Comment by dhaval-shukla** [comment]
Hey

Sorry. Was caught up in a few things.

Yes. I'll share the data tomorrow

**Comment by dhaval-shukla** [comment]
https://drive.google.com/open?id=0B8V7wNW1782vclltZ0tlejZmRm8

this is the link that has the files in it.


I am not able the files here, it says I require push access

So I have shared some files that I on google drive

**Comment by ndkcha** [comment]
We will make a rough architecture on where (or how) to store this data so that developers here can make some amazing analysis tools or apps out of it. 

I will get back to you in a day.

**Comment by shravan91** [comment]
@shukla777 Nice!

@ndkcha Any updates on how can we upload data on the website?

**Comment by ndkcha** [comment]
I and jimish will sit for brainstorm session. We will update as soon as possible. We are also planning to expand collaborators.
The thread will be discussed further here at DatameetAMD/bucket-list#1

**Comment by gnatih** [comment]
Cannot clone the repo locally. Have you initialised it?
