### ISSUE TITLE
GIS data for Ahmedabad

### ISSUE THREAD

**Issue by shravan91** [DatameetAMD/open-ahmedabad-web#5]
I will putting up the GIS data I have for Ahmedabad in the coming weeks. I would like someone to create a tab for 'GIS' specific data for the same on the website.

**Comment by ndkcha** [comment]
Will you upload raw files or in a specific format ? 
How do you suggest the design and specs of the page ?

**Comment by hypothal** [comment]
See what Thej has done for the map files.

**Comment by shravan91** [comment]
@ndkcha Here is an example of Thej has done: http://openbangalore.org/available-data/#gis_maps

**Comment by ndkcha** [comment]
Okay. We will look into it.
The further discussions on this thread will be tracked here at DatameetAMD/bucket-list#3
